# Generated by Django 5.1.6 on 2025-04-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
