# Generated by Django 5.1.2 on 2025-04-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_meetingroom_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='booking.workspace')),
            ],
        ),
    ]
